
package simplexs.gui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import simplexs.logica.SimplexMax;

public class Simplex extends javax.swing.JFrame {

    
    private float x11=0;
    private float x12=0;
    private float x13=0;
    private float x21=0;
    private float x22=0;
    private float x23=0;
    
    private float zx1=0;
    private float zx2=0;
    private float zs1=0;
    private float zs2=0;
    private float zs3=0;
    
    
    private float c1=0;
    private float c2=0;
    private float c3=0;
    private float zConst=0;
    
    private float s11 = 1;
    private float s12 = 0;
    private float s13 = 0;
    private float s21 = 0;
    private float s22 = 1;
    private float s23 = 0;
    private float s31 = 0;
    private float s32 = 0;
    private float s33 = 1;
        
    private float pivote = 0;
    private double pm1 = 0.0;
    private double pm2 = 0.0;
    
    private String text = "";
    
    int filas=4, columnas=6;
    private float[][] matriz = new float[filas][columnas];
    
    
    /**
     * Creates new form Simplex
     */
    public Simplex() {
        initComponents();
        //setDataMatriz();
        setTitle("Job Adolfo Salinas Hernández / 2020670044 / QM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cx30 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cx31 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cx00 = new javax.swing.JTextField();
        cx10 = new javax.swing.JTextField();
        cx21 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cx01 = new javax.swing.JTextField();
        cx11 = new javax.swing.JTextField();
        cx20 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cx05 = new javax.swing.JTextField();
        cx15 = new javax.swing.JTextField();
        cx25 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        vx11 = new javax.swing.JTextField();
        vx12 = new javax.swing.JTextField();
        vx13 = new javax.swing.JTextField();
        vx21 = new javax.swing.JTextField();
        vx22 = new javax.swing.JTextField();
        vx23 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        vc1 = new javax.swing.JTextField();
        vc2 = new javax.swing.JTextField();
        vc3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        vzx1 = new javax.swing.JTextField();
        vzx2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        calculate2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Maximización");

        jLabel2.setText("Z = ");

        cx30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx30ActionPerformed(evt);
            }
        });
        cx30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx30KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx30KeyTyped(evt);
            }
        });

        jLabel3.setText("x1+");

        cx31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx31KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx31KeyTyped(evt);
            }
        });

        jLabel4.setText("x2");

        cx00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx00KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx00KeyTyped(evt);
            }
        });

        cx10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx10KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx10KeyTyped(evt);
            }
        });

        cx21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx21KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx21KeyTyped(evt);
            }
        });

        jLabel5.setText("x1       +");

        jLabel6.setText("x2   ");

        jLabel7.setText("x1       +");

        cx01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx01KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx01KeyTyped(evt);
            }
        });

        cx11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx11ActionPerformed(evt);
            }
        });
        cx11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx11KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx11KeyTyped(evt);
            }
        });

        cx20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx20ActionPerformed(evt);
            }
        });
        cx20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx20KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx20KeyTyped(evt);
            }
        });

        jLabel8.setText("x2   ");

        jLabel9.setText("x1       +");

        jLabel10.setText("x2   ");

        jLabel14.setText("<=");

        jLabel15.setText("<=");

        jLabel16.setText("<=");

        cx05.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx05KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx05KeyTyped(evt);
            }
        });

        cx15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx15KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx15KeyTyped(evt);
            }
        });

        cx25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cx25KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cx25KeyTyped(evt);
            }
        });

        jLabel11.setText("x1, x2  >=  0");

        buttonCalculate.setText("Calcular");
        buttonCalculate.setEnabled(false);
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        jLabel12.setText("x1");

        jLabel13.setText("x2");

        jLabel17.setText("S1");

        jLabel18.setText("S2");

        jLabel19.setText("S3");

        jLabel20.setText("Const");

        vx11.setEditable(false);
        vx11.setEnabled(false);

        vx12.setEditable(false);
        vx12.setEnabled(false);

        vx13.setEditable(false);
        vx13.setEnabled(false);

        vx21.setEditable(false);
        vx21.setEnabled(false);

        vx22.setEditable(false);
        vx22.setEnabled(false);

        vx23.setEditable(false);
        vx23.setEnabled(false);

        jTextField18.setEditable(false);
        jTextField18.setText("1");
        jTextField18.setEnabled(false);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jTextField19.setEditable(false);
        jTextField19.setText("0");
        jTextField19.setEnabled(false);

        jTextField20.setEditable(false);
        jTextField20.setText("0");
        jTextField20.setEnabled(false);

        jTextField21.setText("0");
        jTextField21.setEnabled(false);
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jTextField22.setEditable(false);
        jTextField22.setText("1");
        jTextField22.setEnabled(false);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jTextField23.setEditable(false);
        jTextField23.setText("0");
        jTextField23.setEnabled(false);

        jTextField24.setEditable(false);
        jTextField24.setText("0");
        jTextField24.setEnabled(false);

        jTextField25.setEditable(false);
        jTextField25.setText("0");
        jTextField25.setEnabled(false);

        jTextField26.setEditable(false);
        jTextField26.setText("1");
        jTextField26.setEnabled(false);

        vc1.setEditable(false);
        vc1.setEnabled(false);

        vc2.setEditable(false);
        vc2.setEnabled(false);

        vc3.setEditable(false);
        vc3.setEnabled(false);

        vzx1.setEditable(false);
        vzx1.setEnabled(false);

        vzx2.setEditable(false);
        vzx2.setEnabled(false);

        jTextField3.setEditable(false);
        jTextField3.setText("0");
        jTextField3.setEnabled(false);

        jTextField4.setEditable(false);
        jTextField4.setText("0");
        jTextField4.setEnabled(false);

        jTextField5.setEditable(false);
        jTextField5.setText("0");
        jTextField5.setEnabled(false);

        jTextField6.setEditable(false);
        jTextField6.setText("0");
        jTextField6.setEnabled(false);

        area.setEditable(false);
        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        calculate2.setText("Calculate");
        calculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(vx11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(vx12)
                                            .addComponent(vx13)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel12)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vx21)
                                    .addComponent(vx22, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addComponent(vx23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField18)
                                        .addComponent(jTextField19)
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField21)
                                        .addComponent(jTextField22)
                                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField24)
                                        .addComponent(jTextField25)
                                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20)
                                    .addComponent(vc2)
                                    .addComponent(vc1)
                                    .addComponent(vc3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cx30, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cx31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(cx10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(cx20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel7)
                                                                .addGap(35, 35, 35)))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(cx21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel10))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(cx11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel6))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(cx00, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel5)
                                                        .addGap(35, 35, 35)
                                                        .addComponent(cx01, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel8)))
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cx25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cx15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cx05, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(vzx1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vzx2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(calculate2)
                                .addGap(101, 101, 101)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cx30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cx31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cx00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cx01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel8)
                                        .addComponent(cx05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cx10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cx11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(cx15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel15)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cx21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(cx25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addComponent(cx20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculate2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vx11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vx12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vx13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vx23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vx21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vx22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(vc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(vc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vzx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vzx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cx30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx30ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void cx30KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx30KeyReleased
        zx1 = Float.parseFloat(cx30.getText())*-1;
        vzx1.setText(zx1+"");
        area.setText("");
    }//GEN-LAST:event_cx30KeyReleased

    private void cx30KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx30KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx30.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx30KeyTyped

    private void cx31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx31KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx31.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx31KeyTyped

    private void cx00KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx00KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx00.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx00KeyTyped

    private void cx10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx10KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx10.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx10KeyTyped

    private void cx20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx20KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx20.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx20KeyTyped

    private void cx01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx01KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx01.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx01KeyTyped

    private void cx11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx11KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx11.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx11KeyTyped

    private void cx21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx21KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & cx21.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx21KeyTyped

    private void cx05KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx05KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & vc1.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx05KeyTyped

    private void cx15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx15KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & vc2.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx15KeyTyped

    private void cx25KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx25KeyTyped
        // Si el usuario introduce un valor que no sea decimal..
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) & c!='.' & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // Se acepta que el usuario introduzca un punto pero sólo uno
        if(c=='.' & vc1.getText().contains(".") & (c != KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Sólo se pueden ingresar números decimales en este campo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cx25KeyTyped

    private void cx31KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx31KeyReleased
        zx2 = Float.parseFloat(cx31.getText())*-1;
        vzx2.setText(zx2+"");
        area.setText("");
    }//GEN-LAST:event_cx31KeyReleased

    private void cx00KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx00KeyReleased
        x11 = Float.parseFloat(cx00.getText());
        vx11.setText(x11+"");
        area.setText("");
    }//GEN-LAST:event_cx00KeyReleased

    private void cx10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx10KeyReleased
        x12 = Float.parseFloat(cx10.getText());
        vx12.setText(x12+"");
        area.setText("");
    }//GEN-LAST:event_cx10KeyReleased

    private void cx20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx20KeyReleased
        x13 = Float.parseFloat(cx20.getText());
        vx13.setText(x13+"");
        area.setText("");
    }//GEN-LAST:event_cx20KeyReleased

    private void cx01KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx01KeyReleased
        x21 = Float.parseFloat(cx01.getText());
        vx21.setText(x21+"");
        area.setText("");
    }//GEN-LAST:event_cx01KeyReleased

    private void cx11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx11KeyReleased
        x22 = Float.parseFloat(cx11.getText());
        vx22.setText(x22+"");
        area.setText("");
    }//GEN-LAST:event_cx11KeyReleased

    private void cx21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx21KeyReleased
        x23 = Float.parseFloat(cx21.getText());
        vx23.setText(x23+"");
        area.setText("");
    }//GEN-LAST:event_cx21KeyReleased

    private void cx05KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx05KeyReleased
        c1 = Float.parseFloat(cx05.getText());
        vc1.setText(c1+"");
        area.setText("");
    }//GEN-LAST:event_cx05KeyReleased

    private void cx15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx15KeyReleased
        c2 = Float.parseFloat(cx15.getText());
        vc2.setText(c2+"");
        area.setText("");
    }//GEN-LAST:event_cx15KeyReleased

    private void cx25KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cx25KeyReleased
        c3 = Float.parseFloat(cx25.getText());
        vc3.setText(c3+"");
        area.setText("");
    }//GEN-LAST:event_cx25KeyReleased

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        /*
        if(zx1<0 && zx2<0) {
            float m1,m2,m3;
            if(zx1 < zx2) {
                m1 = c1 / x11;
                m2 = c2 / x12;
                m3 = c3 / x13;
                switch(Comparator.compareThree(m1, m2, m3)){
                    case 1:
                        pivote = x11;
                        break;
                    case 2:
                        pivote = x12;
                        break;
                    case 3:
                        pivote = x13;
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Caso no previsto");
                        break;
                }
            }
            else {
                m1 = c1 / x21;
                m2 = c2 / x22;
                m3 = c3 / x23;
                switch(Comparator.compareThree(m1, m2, m3)){
                    case 1:
                        pivote = x21;
                        break;
                    case 2:
                        pivote = x22;
                        break;
                    case 3:
                        pivote = x23;
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Caso no previsto");
                        break;
                }
            }
                text += "Pivote: " + pivote + "\n\n";
                pm1 = 1 / pivote;
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+"*(1/"+pivote + ")\t|\t" + x21+ "*(1/"+pivote + ")\t|\t" +
                        s11+"*(1/"+pivote+")\t|\t" +
                        s21+"*(1/"+pivote+")\t|\t"+
                        s31+"*(1/"+pivote+")" +
                        "\t\t||\t" + c1+"*(1/"+pivote+")\n" ;
                text += x12+"\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text += x13+"\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                x11 *= pm1;
                x21 *= pm1;
                s11 *= pm1;
                s21 *= pm1;
                s31 *= pm1;
                c1 *= pm1;
                text += "\n\n";
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text += x12+ "\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text += x13+ "\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                
                float cleanerLine = x12 * -1;
                text += "\n\n";
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text +=          cleanerLine + "*"+x11+"+"+ x12 +
                       "\t|\t" + cleanerLine + "*"+x21+"+" +x22+ "\t|\t" +
                                 cleanerLine + "*"+s11+"+" +s12+ 
                        "\t|\t" +cleanerLine + "*"+s21+"+" +s22+ 
                        "\t|\t" +cleanerLine + "*"+s31+"+" +s32+
                        "\t\t||\t"+ cleanerLine + "*"+c1+"+" +c2+ "\n" ;
                text += x13+ "\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                
                x12 += cleanerLine * x11;
                x22 += cleanerLine * x21;
                s12 += cleanerLine * s11;
                s22 += cleanerLine * s21;
                s32 += cleanerLine * s31;
                c2 += cleanerLine * c1;
                text += "\n\n";
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text += x12+ "\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text += x13+ "\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                
                text += "\n\n";
                cleanerLine = x13 * -1;
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text += x12+ "\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text +=          cleanerLine + "*"+x11+"+"+  x13+ 
                        "\t|\t" +cleanerLine + "*"+x21+"+" +x23+ 
                        "\t|\t" +cleanerLine + "*"+s11+"+" +s13+ 
                        "\t|\t" +cleanerLine + "*"+s21+"+" +s23+ 
                        "\t|\t" +cleanerLine + "*"+s31+"+" +s33+ 
                      "\t\t||\t" +cleanerLine + "*"+c1+"+" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                
                x13 += cleanerLine * x11;
                x23 += cleanerLine * x21;
                s13 += cleanerLine * s11;
                s23 += cleanerLine * s21;
                s33 += cleanerLine * s31;
                c3 += cleanerLine * c1;
                text += "\n\n";
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text += x12+ "\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text += x13+ "\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                
                text += "\n\n";
                cleanerLine = zx1 * -1;
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text += x12+ "\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text += x13+ "\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text +=          cleanerLine + "*"+x11+"+"+zx1+
                        "\t|\t" +cleanerLine + "*"+x21+"+" +zx2+ 
                        "\t|\t" +cleanerLine + "*"+s11+"+" +zs1+ 
                        "\t|\t" +cleanerLine + "*"+s21+"+" +zs2+ 
                        "\t|\t" +cleanerLine + "*"+s31+"+" +zs3+ 
                     "\t\t||\t" +cleanerLine + "*"+c1+"+" +zConst+ "\n" ;
                
                zx1 += cleanerLine * x11;
                zx2 += cleanerLine * x21;
                zs1 += cleanerLine * s11;
                zs2 += cleanerLine * s21;
                zs3 += cleanerLine * s31;
                zConst += cleanerLine * c1;
                text += "\n\n";
                text += "x1\t|\tx2\t|\tS1\t|\tS2\t|\tS3\t\t||\tConst\n";
                text += "--\t|\t--\t|\t---\t|\t---\t|\t---\t\t||\t-----\n";
                text += x11+ "\t|\t" +x21+ "\t|\t" +s11+ "\t|\t" +s21+ "\t|\t" +s31+ "\t\t||\t" +c1+ "\n" ;
                text += x12+ "\t|\t" +x22+ "\t|\t" +s12+ "\t|\t" +s22+ "\t|\t" +s32+ "\t\t||\t" +c2+ "\n" ;
                text += x13+ "\t|\t" +x23+ "\t|\t" +s13+ "\t|\t" +s23+ "\t|\t" +s33+ "\t\t||\t" +c3+ "\n" ;
                text += "-----\t|\t-----\t|\t-----\t|\t-----\t|\t-----\t\t||\t-----\n";
                text += zx1+"\t|\t" +zx2+ "\t|\t" +zs1+ "\t|\t" +zs2+ "\t|\t" +zs3+ "\t\t||\t" +zConst+ "\n" ;
                
                text += "\n\n\n";
                float mm1 = c1 / x21;
                float mm2 = c2 / x22;
                float mm3 = c3 / x23;
                switch(Comparator.compareThree(mm1, mm2, mm3)){
                    case 1:
                        pivote = x21;
                        break;
                    case 2:
                        pivote = x22;
                        break;
                    case 3:
                        pivote = x23;
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Caso no previsto");
                        break;
                }
                
                desplegar();
        }
        */
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void cx20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx20ActionPerformed

    private void calculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate2ActionPerformed
        
        setDataMatriz();
        SimplexMax sm = new SimplexMax(matriz, pivote, filas, columnas);
        text = sm.calculate();
        desplegar();
        
    }//GEN-LAST:event_calculate2ActionPerformed

    private void cx11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cx11ActionPerformed

    
    
    public void desplegar(){
        area.append(text);
    }
    
    
    public void setData(){
        
        x11 = Float.parseFloat(vx11.getText());
        x12 = Float.parseFloat(vx12.getText());
        x13 = Float.parseFloat(vx13.getText());
        x21 = Float.parseFloat(vx21.getText());
        x22 = Float.parseFloat(vx22.getText());
        x23 = Float.parseFloat(vx23.getText());
        c1 = Float.parseFloat(vc1.getText());
        c2 = Float.parseFloat(vc2.getText());
        c3 = Float.parseFloat(vc3.getText());
        zx1 = Float.parseFloat(vzx1.getText())*-1;
        zx2 = Float.parseFloat(vzx2.getText())*-1;
        
    }
    
    public void setDataMatriz(){
        
        matriz[0][0] = Float.parseFloat(cx00.getText());
        matriz[0][1] = Float.parseFloat(cx01.getText());
        matriz[0][2] = 1;
        matriz[0][3] = 0;
        matriz[0][4] = 0;
        matriz[0][5] = Float.parseFloat(cx05.getText());
        
        matriz[1][0] = Float.parseFloat(cx10.getText());
        matriz[1][1] = Float.parseFloat(cx11.getText());
        matriz[1][2] = 0;
        matriz[1][3] = 1;
        matriz[1][4] = 0;
        matriz[1][5] = Float.parseFloat(cx15.getText());
        
        matriz[2][0] = Float.parseFloat(cx20.getText());
        matriz[2][1] = Float.parseFloat(cx21.getText());
        matriz[2][2] = 0;
        matriz[2][3] = 0;
        matriz[2][4] = 1;
        matriz[2][5] = Float.parseFloat(cx25.getText());
        
        matriz[3][0] = Float.parseFloat(cx30.getText()) * -1;
        matriz[3][1] = Float.parseFloat(cx31.getText()) * -1;
        matriz[3][2] = 0;
        matriz[3][3] = 0;
        matriz[3][4] = 0;
        matriz[3][5] = 0;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton calculate2;
    private javax.swing.JTextField cx00;
    private javax.swing.JTextField cx01;
    private javax.swing.JTextField cx05;
    private javax.swing.JTextField cx10;
    private javax.swing.JTextField cx11;
    private javax.swing.JTextField cx15;
    private javax.swing.JTextField cx20;
    private javax.swing.JTextField cx21;
    private javax.swing.JTextField cx25;
    private javax.swing.JTextField cx30;
    private javax.swing.JTextField cx31;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField vc1;
    private javax.swing.JTextField vc2;
    private javax.swing.JTextField vc3;
    private javax.swing.JTextField vx11;
    private javax.swing.JTextField vx12;
    private javax.swing.JTextField vx13;
    private javax.swing.JTextField vx21;
    private javax.swing.JTextField vx22;
    private javax.swing.JTextField vx23;
    private javax.swing.JTextField vzx1;
    private javax.swing.JTextField vzx2;
    // End of variables declaration//GEN-END:variables
}
